/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Listen for push events
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'Pulse';
    const options: any = {
      body: data.body || 'You have a new message.',
      icon: '/pwa-192x192.png',
      badge: '/mask-icon.svg',
      actions: data.actions || [],
      data: {
        url: data.url || '/',
        entryId: data.entryId || null
      }
    };

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (err) {
    console.error('Error parsing push payload', err);
  }
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const action = event.action;
  const urlToOpen = event.notification.data.url || '/';
  const entryId = event.notification.data.entryId;

  // "Yes, still doing it"
  if (action === 'ignore') {
    return;
  }

  const handleNotificationAction = async () => {
    // "No, stop timer"
    if (action === 'stop' && entryId) {
      try {
        const now = new Date();
        const end_time = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
        // Automatically end the entry in the background
        await fetch(`/api/entries/${entryId}/finish`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ end_time })
        });
      } catch (err) {
        console.error('Failed to stop timer from SW:', err);
      }
    }

    // Direct user to app
    const windowClients = await self.clients.matchAll({ type: 'window' });
    for (let i = 0; i < windowClients.length; i++) {
      const client = windowClients[i];
      if (client.url === urlToOpen && 'focus' in client) {
        return client.focus();
      }
    }
    if (self.clients.openWindow) {
      return self.clients.openWindow(urlToOpen);
    }
  };

  event.waitUntil(handleNotificationAction());
});
